// +build !ignore_autogenerated

/*
simple-kubernetes-test-environment

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by deepcopy-gen. DO NOT EDIT.

package config

import (
	net "net"

	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LinuxVirtualSwitchConfig) DeepCopyInto(out *LinuxVirtualSwitchConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.PublicIPAddr != nil {
		in, out := &in.PublicIPAddr, &out.PublicIPAddr
		*out = make(net.IP, len(*in))
		copy(*out, *in)
	}
	if in.PrivateIPAddr != nil {
		in, out := &in.PrivateIPAddr, &out.PrivateIPAddr
		*out = make(net.IP, len(*in))
		copy(*out, *in)
	}
	in.SSH.DeepCopyInto(&out.SSH)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LinuxVirtualSwitchConfig.
func (in *LinuxVirtualSwitchConfig) DeepCopy() *LinuxVirtualSwitchConfig {
	if in == nil {
		return nil
	}
	out := new(LinuxVirtualSwitchConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LinuxVirtualSwitchConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineNetworkConfig) DeepCopyInto(out *MachineNetworkConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Interfaces != nil {
		in, out := &in.Interfaces, &out.Interfaces
		*out = make([]NetworkInterfaceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Nameservers != nil {
		in, out := &in.Nameservers, &out.Nameservers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineNetworkConfig.
func (in *MachineNetworkConfig) DeepCopy() *MachineNetworkConfig {
	if in == nil {
		return nil
	}
	out := new(MachineNetworkConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineNetworkConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInterfaceConfig) DeepCopyInto(out *NetworkInterfaceConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.IPAddr != nil {
		in, out := &in.IPAddr, &out.IPAddr
		*out = make(net.IP, len(*in))
		copy(*out, *in)
	}
	if in.GatewayIPAddr != nil {
		in, out := &in.GatewayIPAddr, &out.GatewayIPAddr
		*out = make(net.IP, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInterfaceConfig.
func (in *NetworkInterfaceConfig) DeepCopy() *NetworkInterfaceConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkInterfaceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NetworkInterfaceConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHCredential) DeepCopyInto(out *SSHCredential) {
	*out = *in
	if in.PrivateKey != nil {
		in, out := &in.PrivateKey, &out.PrivateKey
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	if in.PublicKey != nil {
		in, out := &in.PublicKey, &out.PublicKey
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHCredential.
func (in *SSHCredential) DeepCopy() *SSHCredential {
	if in == nil {
		return nil
	}
	out := new(SSHCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHCredentialAndEndpoint) DeepCopyInto(out *SSHCredentialAndEndpoint) {
	*out = *in
	in.SSHCredential.DeepCopyInto(&out.SSHCredential)
	in.SSHEndpoint.DeepCopyInto(&out.SSHEndpoint)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHCredentialAndEndpoint.
func (in *SSHCredentialAndEndpoint) DeepCopy() *SSHCredentialAndEndpoint {
	if in == nil {
		return nil
	}
	out := new(SSHCredentialAndEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHCredentialConfig) DeepCopyInto(out *SSHCredentialConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.SSHCredential.DeepCopyInto(&out.SSHCredential)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHCredentialConfig.
func (in *SSHCredentialConfig) DeepCopy() *SSHCredentialConfig {
	if in == nil {
		return nil
	}
	out := new(SSHCredentialConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SSHCredentialConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHEndpoint) DeepCopyInto(out *SSHEndpoint) {
	*out = *in
	out.ServiceEndpoint = in.ServiceEndpoint
	if in.ProxyHost != nil {
		in, out := &in.ProxyHost, &out.ProxyHost
		*out = new(SSHEndpoint)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHEndpoint.
func (in *SSHEndpoint) DeepCopy() *SSHEndpoint {
	if in == nil {
		return nil
	}
	out := new(SSHEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHEndpointConfig) DeepCopyInto(out *SSHEndpointConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.SSHEndpoint.DeepCopyInto(&out.SSHEndpoint)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHEndpointConfig.
func (in *SSHEndpointConfig) DeepCopy() *SSHEndpointConfig {
	if in == nil {
		return nil
	}
	out := new(SSHEndpointConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SSHEndpointConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceEndpoint) DeepCopyInto(out *ServiceEndpoint) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceEndpoint.
func (in *ServiceEndpoint) DeepCopy() *ServiceEndpoint {
	if in == nil {
		return nil
	}
	out := new(ServiceEndpoint)
	in.DeepCopyInto(out)
	return out
}
